### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by littlee** [teambition/Hire#3]
![企业微信20210723-154911](https://user-images.githubusercontent.com/7534668/126752570-c6e28aaa-784f-4204-abe8-781e39766c1a.png)

**Comment by Saviio** [comment]
@littlee 

Sorry for inconveniencing you. we noticed this problem for some time. therefore, our tech team planning to use a new hybrid architecture to improve this situation. we believe these improvement will be shipped in the coming months.

Thanks for caring about our product.

Best regards.
